-- V4-P1 chips 池 v3：在原 14 条之外再插入 32 条
-- 业主反馈"问题不够具体"，按 8 大场景批量补充画面感强的高发场景
-- 池子扩到 46 条；iOS 每次新对话从池中随机抽 4 个展示

INSERT INTO "onboarding_chips" ("id", "order_idx", "label_zh", "label_en", "icon_type", "action_type", "action_payload_zh", "action_payload_en", "status", "updated_at") VALUES

-- ========== A. 冒充官方/公检法/客服（最高发 + 长辈易中）==========
(gen_random_uuid()::text, 15,
 '自称"公安局"打电话说我涉嫌洗钱怎么办？', '"Police" called saying I''m suspected of money laundering, what should I do?',
 'shield.lefthalf.filled', 'text',
 '自称"公安局"打电话说我涉嫌洗钱怎么办？', '"Police" called saying I''m suspected of money laundering, what should I do?',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 16,
 '派出所要我把钱转到"安全账户"', 'Police want me to transfer money to a "safe account"',
 'shield.lefthalf.filled', 'text',
 '派出所要我把钱转到"安全账户"', 'Police want me to transfer money to a "safe account"',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 17,
 '"网警"让我下载远程控制 App 配合调查', '"Cybercrime officer" wants me to install remote-control app for investigation',
 'shield.lefthalf.filled', 'text',
 '"网警"让我下载远程控制 App 配合调查', '"Cybercrime officer" wants me to install remote-control app for investigation',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 18,
 '银行客服打来要我读验证码核实', 'Bank rep called asking me to read the verification code',
 'person.badge.shield.checkmark', 'text',
 '银行客服打来要我读验证码核实', 'Bank rep called asking me to read the verification code',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 19,
 '客户经理说我贷款过了，先付 3000 服务费', 'Loan officer says my loan is approved, asks for 3000 service fee first',
 'creditcard.fill', 'text',
 '客户经理说我贷款过了，先付 3000 服务费', 'Loan officer says my loan is approved, asks for 3000 service fee first',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 20,
 '自称医院说孩子出车祸要急救费', '"Hospital" calling says my child had an accident and needs emergency fee',
 'phone.fill', 'text',
 '自称医院说孩子出车祸要急救费', '"Hospital" calling says my child had an accident and needs emergency fee',
 'active', CURRENT_TIMESTAMP),

-- ========== B. 投资理财类（金额最大）==========
(gen_random_uuid()::text, 21,
 '群里"老师"带单几次都准，让我充 5 万跟单', 'Group "mentor" hit several trades, asks me to deposit 50K to follow',
 'chart.line.uptrend.xyaxis', 'text',
 '群里"老师"带单几次都准，让我充 5 万跟单', 'Group "mentor" hit several trades, asks me to deposit 50K to follow',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 22,
 '有人推荐 80% 收益的"量化项目"靠谱吗？', 'Someone pitching a "quant project" with 80% return — is it real?',
 'chart.line.uptrend.xyaxis', 'text',
 '有人推荐 80% 收益的"量化项目"靠谱吗？', 'Someone pitching a "quant project" with 80% return — is it real?',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 23,
 '让我下载一个海外股票 App 投资', 'They want me to install an overseas stock-trading app',
 'chart.line.uptrend.xyaxis', 'text',
 '让我下载一个海外股票 App 投资', 'They want me to install an overseas stock-trading app',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 24,
 '数字货币交易所先充值再返佣金', 'Crypto exchange wants me to deposit first and "earn commission"',
 'chart.line.uptrend.xyaxis', 'text',
 '数字货币交易所先充值再返佣金', 'Crypto exchange wants me to deposit first and "earn commission"',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 25,
 '"内部炒股群"先免费体验 7 天', '"Insider trading group" offers a free 7-day trial',
 'chart.line.uptrend.xyaxis', 'text',
 '"内部炒股群"先免费体验 7 天', '"Insider trading group" offers a free 7-day trial',
 'active', CURRENT_TIMESTAMP),

-- ========== C. 网购/退款类（覆盖所有人）==========
(gen_random_uuid()::text, 26,
 '客服说我商品质量问题要赔我钱，让我加 QQ', '"Support" says my item has defects and wants to refund — asks me to add QQ',
 'shippingbox.fill', 'text',
 '客服说我商品质量问题要赔我钱，让我加 QQ', '"Support" says my item has defects and wants to refund — asks me to add QQ',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 27,
 '快递员说包裹丢了要赔我 3 倍', 'Courier says my package is lost and offers 3x compensation',
 'shippingbox.fill', 'text',
 '快递员说包裹丢了要赔我 3 倍', 'Courier says my package is lost and offers 3x compensation',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 28,
 '退款客服让我开屏幕共享操作', '"Refund support" wants me to share my screen',
 'shippingbox.fill', 'text',
 '退款客服让我开屏幕共享操作', '"Refund support" wants me to share my screen',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 29,
 '商家说扫码退款要填银行卡密码', 'Merchant asks me to scan a QR and enter my bank card PIN to get refund',
 'creditcard.fill', 'text',
 '商家说扫码退款要填银行卡密码', 'Merchant asks me to scan a QR and enter my bank card PIN to get refund',
 'active', CURRENT_TIMESTAMP),

-- ========== D. 短信链接（高发，1 秒决策类）==========
(gen_random_uuid()::text, 30,
 '短信说 ETC 即将失效，要点链接更新', 'SMS says my ETC pass is about to expire — must click link to renew',
 'envelope.badge', 'text',
 '短信说 ETC 即将失效，要点链接更新', 'SMS says my ETC pass is about to expire — must click link to renew',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 31,
 '短信说我手机欠费停机，链接缴费', 'SMS says my phone will be cut off for unpaid bill — link to pay',
 'envelope.badge', 'text',
 '短信说我手机欠费停机，链接缴费', 'SMS says my phone will be cut off for unpaid bill — link to pay',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 32,
 '短信带链接说我"支付宝异地登录"安全吗？', 'SMS with link says "Alipay logged in from another location" — safe?',
 'envelope.badge', 'text',
 '短信带链接说我"支付宝异地登录"安全吗？', 'SMS with link says "Alipay logged in from another location" — safe?',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 33,
 '短信说"积分即将到期"要点链接兑换', 'SMS says my "points are expiring soon" — click to redeem',
 'envelope.badge', 'text',
 '短信说"积分即将到期"要点链接兑换', 'SMS says my "points are expiring soon" — click to redeem',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 34,
 '顺丰快递通知说有"待取件"短信带链接', 'SF Express SMS says "package waiting for pickup" with a link',
 'shippingbox.fill', 'text',
 '顺丰快递通知说有"待取件"短信带链接', 'SF Express SMS says "package waiting for pickup" with a link',
 'active', CURRENT_TIMESTAMP),

-- ========== E. 冒充亲友/同事（情感勒索）==========
(gen_random_uuid()::text, 35,
 '儿子用陌生号码发"我手机丢了"借 5000', 'My son texted from an unknown number "I lost my phone, lend me 5000"',
 'person.crop.circle.badge.exclamationmark', 'text',
 '儿子用陌生号码发"我手机丢了"借 5000', 'My son texted from an unknown number "I lost my phone, lend me 5000"',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 36,
 '老板深夜微信让我紧急转账给客户', 'My boss messaged late at night asking me to wire money to a client',
 'person.crop.circle.badge.exclamationmark', 'text',
 '老板深夜微信让我紧急转账给客户', 'My boss messaged late at night asking me to wire money to a client',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 37,
 '同事让我帮忙接收一个验证码', 'A coworker asks me to receive a verification code for them',
 'envelope.badge', 'text',
 '同事让我帮忙接收一个验证码', 'A coworker asks me to receive a verification code for them',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 38,
 '微信加我说是高中同学要借钱', 'A WeChat add says they''re an old classmate and wants to borrow money',
 'message.fill', 'text',
 '微信加我说是高中同学要借钱', 'A WeChat add says they''re an old classmate and wants to borrow money',
 'active', CURRENT_TIMESTAMP),

-- ========== F. 红包/中奖/活动（占便宜心理）==========
(gen_random_uuid()::text, 39,
 '扫码领 200 元红包要填身份证号', 'Scan a QR for a 200 RMB gift — they want my ID number',
 'gift.fill', 'text',
 '扫码领 200 元红包要填身份证号', 'Scan a QR for a 200 RMB gift — they want my ID number',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 40,
 '集 8 张卡瓜分 100 万的活动靠谱吗？', '"Collect 8 cards to split 1M RMB" — is it real?',
 'gift.fill', 'text',
 '集 8 张卡瓜分 100 万的活动靠谱吗？', '"Collect 8 cards to split 1M RMB" — is it real?',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 41,
 '中签新股要先付 5000 元保证金', 'I "won an IPO lottery" but need to pay 5000 RMB deposit first',
 'chart.line.uptrend.xyaxis', 'text',
 '中签新股要先付 5000 元保证金', 'I "won an IPO lottery" but need to pay 5000 RMB deposit first',
 'active', CURRENT_TIMESTAMP),

-- ========== G. 兼职刷单/招聘（学生/宝妈）==========
(gen_random_uuid()::text, 42,
 '京东兼职刷单先垫付返佣金能做吗？', '"JD task-rebate" side gig with upfront payment — legit?',
 'briefcase.fill', 'text',
 '京东兼职刷单先垫付返佣金能做吗？', '"JD task-rebate" side gig with upfront payment — legit?',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 43,
 '抖音点赞员日结工资先做任务', '"TikTok like-clicker" with daily pay — must do tasks first',
 'briefcase.fill', 'text',
 '抖音点赞员日结工资先做任务', '"TikTok like-clicker" with daily pay — must do tasks first',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 44,
 '招聘说手机就能做网络兼职', 'Recruitment ad says I can do online gig work from my phone',
 'briefcase.fill', 'text',
 '招聘说手机就能做网络兼职', 'Recruitment ad says I can do online gig work from my phone',
 'active', CURRENT_TIMESTAMP),

-- ========== H. 情感/网恋诈骗 ==========
(gen_random_uuid()::text, 45,
 '网上认识的外国人寄包裹要我付清关费', 'An overseas friend I met online sent a package — wants me to pay customs',
 'person.crop.circle.badge.exclamationmark', 'text',
 '网上认识的外国人寄包裹要我付清关费', 'An overseas friend I met online sent a package — wants me to pay customs',
 'active', CURRENT_TIMESTAMP),
(gen_random_uuid()::text, 46,
 '网恋对象推荐我跟他一起投资', 'My online romantic partner wants me to invest together with them',
 'person.crop.circle.badge.exclamationmark', 'text',
 '网恋对象推荐我跟他一起投资', 'My online romantic partner wants me to invest together with them',
 'active', CURRENT_TIMESTAMP);
